baseURL = "https://blogtitle.github.io/"
languageCode = "en-us"
title = "Blog Title"
theme = "hugo-natrium-multiple-authors-theme"
preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "native"

[taxonomies]
    category = "categories"  
    tag = "tags"
    author = "authors"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -110
    
[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = -120

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = -130

[[menu.main]]
    name = "Authors"
    url = "/authors"
    weight = -140

[params]
    description = ""

    [params.logo]
    url = "clorine.png"
    width = 50
    height = 50
    alt = "Logo"

    [params.authors.anna]
    id = "anna"
    firstName = "Anna"
    lastName = "Bernardi"

    [params.authors.rob]
    id = "roberto"
    firstName = "Roberto"
    lastName = "Clapis"
