baseURL = "https://blogtitle.github.io/"
languageCode = "en-us"
title = "Blog Title"
theme = "hugo-natrium-theme"
preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "native"

[taxonomies]
    category = "authors"  
    tag = "tags"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -110
    
[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = -120

[[menu.main]]
    name = "Authors"
    url = "/authors"
    weight = -130

[params]
    description = ""

    [params.logo]
    url = "gopher.png"
    width = 50
    height = 50
    alt = "Logo"
